### ISSUE TITLE
Компоненты - Button

### ISSUE THREAD

**Issue by peter-nikitin** [Telegads/issues#36]
# Биг Пикча

Нужно сделать компонент кнопки
Он должен соответсвовать дизайну из фигмы: https://www.figma.com/file/FBuGmZ4XgWoYAuZA4uyAfk/TelegAds?node-id=64%3A43

Один компонент с помощью разных пропсов рисует разные кнопки. 

Должен уметь в сосотяния:
- обычное
- ховер
- нажато
- загрузка
- дизейбл

# Дод

- есть единый компонент для кнопки

# Реализация

В рамках этой задачи мы ожидаем предложение по реализации нашей библиотеки копмонентов. 
Хочется взять готовую либу и допилить ее под наш дизайн. 
Видится 2 варианта: бутстрап или tailwind
Какая-то верстка уже есть, можно частично переиспользовать ее

**Comment by anerix** [comment]
после просмотра разницы между статик вёрсткой и приложением были обнаруженые следующие проблемы:

главная страница:
десктоп:
- header левое облако перенести со статики
- секция 01 02 03... проверить отступы по макету, перенести стили вёрстки со статики
- блок регистрация с фоном - пофиксить, по макету фон занимает всю ширину (нет на fullhd)
- в приложении нет футера, перенести
- блок возникли вопросы - кнопки связи справа не по макету, доделать
- футер - предлагаю вместо text decoration underline сделать border bottom
- блок из 3 карточек с цифрами - в приложении светятся 2, должна одна в центре, пофиксить
- доделать меню + переименовать кнопку в вход/регистрация, как на макете и статике

адаптив таблет:
- стилей для адаптива нет в приложении, перенести
- регистрация с фоном (десктоп пункт 3) так же фикс
- блок с 3 кнопками написать в соц-сети, по макету должен быть фон, его нет, доделать
- левое облако (десктоп пункт 1) находится не по макету, пофиксить

адаптив мобильный:
- перенести недостающие стили из статики
- в хедере плывёт фон при снижении до 320px, пофиксить

мобильное меню:
- предлагаю добавить какой-нибудь transition эффект для открытия/закрытия мобильного меню
- доверстать активное состояние ссылок


каталог: 
- в приложении зайти не смог, проблема какая-то User prisma was denied access on the database exchange.public - в статике вёрстка есть но надо немного допилить (кнопка)
- меню слева: допилить отступ от линии при ховере

В остальном вроде нормально, но при самом переносе стоит смотреть пиксель-перфект

**Comment by anerix** [comment]
Было принято решение использовать react bootstrap для построения компонентов своего UI-кита, начинаю это делать

**Comment by anerix** [comment]
предварительная оценка на всю задачу: 15 часов

на момент написания этого коммента на задачу потратил 7:20

**Comment by anerix** [comment]
сделал компонент кнопки, создал пулл-реквесты на текущие исправления вёрстки и т.д
начал переделывать компоненти Header под bootstrap, частично готово (у меня локально коммит в отдельной ветке)
планирую доделывать по чекбоксам и как-то сортировать стили в index.module.scss и catalog.module.scss (заметил много дублирующих + есть проблемы с адаптивом по всей видимости из-за того что на главной странице никак не работают стили из catalog модуля)

потратил на всё 3 часа

**Comment by anerix** [comment]
зарефакторил main.scss и index.module.scss + поправил всю вёрстку в таблет адаптиве на главной странице

https://github.com/Telegads/exchange/pull/28/commits/44af9274e5885f65b09acb27a033fd243a14de43
https://github.com/Telegads/exchange/pull/28/commits/62e462430eb0cd651531e99f9856228549f6880d (исправление опечатки)

осталось поправить мобильный адаптив (пара блоков)

всего по задаче: 14 ч. 20 мин.

**Comment by anerix** [comment]
всё что планировал - сделал. по задаче вышло 16 часов (15 план) по задаче вышло 14:40 + 1:20 на решение конфликтов в пулл реквестах
