### ISSUE TITLE
Добавить нотификации в интерфейсе

### ISSUE THREAD

**Issue by peter-nikitin** [Telegads/issues#40]
# Биг пикча

Сейчас, когда мы не смогли отправить запрос к АПИ или оно ответило с ошибкой, мы бросаем ошибку только в консоль. Пользователь об этом ничего не знает. Это надо исправить

Для этого надо 
- добавить в проект react-toastify
- подключить его глобально к проекту
- сделать хук useUserNotification, который будет возвращать функцию добавления нотификации 
- создавать нотификацию, если неавторизованный пользователь пробует добавить канал в корзину

Текст нотификации
"Для добавления канала в корзину, авторизуйтесь" 

Текст должен быть локализован

# Дод
- при попытке добавить канал неавторизованный пользователь видит нотификацию

**Comment by xNa1D** [comment]
6 часов. Оплачено
