### ISSUE TITLE
Убрать моргание каналов при смене фильтра (лоадинг стейт)

### ISSUE THREAD

**Issue by peter-nikitin** [Telegads/issues#43]
# БигПикча

Сейчас на странице каталога, при применении фильтра, моргают каналы.
Это происходит, потому что у компонента есть 2 источника данных: то что пришло в пропсах при рендере и результат фетча в рантайме

Это выглядет плохо, надо поправить

Есть вот такая штука: https://medium.com/creditas-tech/react-suspense-swr-skeleton-e1979e9f32f0
Возможно она нам поможет 

# Дод
- при применении нового фильтра показывается "лоадер" и потом показываются новые результат фетча по фильтру

**Comment by ireull** [comment]
Потратил 7 часов

**Comment by xNa1D** [comment]
@ireull а можешь расписать на что ушло 7 часов? 
я смотрю pr и в нем +43 -19 строчек. Не оч понимаю откуда такая оценка, с учетом что используется готовый компонент без стилизации.

**Comment by ireull** [comment]
Большая часть времени ушла на поиск инфы про react-suspense с next.js около 3-4 часов и попытками это имплементировать, после того как я написал Пете по поводу проблемы с супенсом и невозможностью это сделать с 17 версией реакта и мы от этого отказались, но я добавил эти попытки в работу

**Comment by xNa1D** [comment]
@ireull я конечно заплачу по оценке, но неожиданно, что за это нужно платить. 
@peter-nikitin @ireull Все больше склоняюсь к оценке карточки до и фиксации этой оценки в отрыве от финальной. 
В предварительной оценке уже поломалось, ее нет
