### ISSUE TITLE
Навигация в левой части экрана

### ISSUE THREAD

**Issue by peter-nikitin** [Telegads/issues#52]
# Биг Пикча

В макетах и верстке у нас есть левая панель с навигацией. 

Ее надо добавить в приложение

Пока там будет 1 пукнт - мои кампании. Ведет на страницу `/campaign` 

Верстка лежит в репозитории с ишьями

# Дод

- есть панель с навигаций в левой части экрана

**Comment by ireull** [comment]
Потратил 2 часа

**Comment by xNa1D** [comment]
оплатил
